spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:50010
              predicates:
              - Path=/users/**
            - id: universe-service
              uri: http://localhost:50020
              predicates:
              - Path=/universes/**
            - id: file-service
              uri: http://localhost:50030
              predicates:
                - Path=/files/**